DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites (
fav_id SERIAL PRIMARY KEY NOT NULL,
place_id INTEGER REFERENCES place(id) ON DELETE CASCADE,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
