DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS places CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;




CREATE TABLE places (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
region VARCHAR(255) NOT NULL,
lat DECIMAL NOT NULL,
lon DECIMAL NOT NULL,
type VARCHAR(255)
)



CREATE TABLE users (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255),
password VARCHAR(255)
);

CREATE TABLE comments (
id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
place_id INTEGER REFERENCES places(id) ON DELETE CASCADE,
content VARCHAR(255) NOT NULL,
comment_date TIMESTAMPTZ
)

CREATE TABLE favourites (
id SERIAL PRIMARY KEY NOT NULL,
place_id INTEGER REFERENCES places(id) ON DELETE CASCADE,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
